/*
 * HLED_config.h
 *
 *  Created on: Aug 13, 2023
 *      Author: Amr-a
 */

#ifndef HLED_CONFIG_H_
#define HLED_CONFIG_H_

#define LED_PORTA_P0_ACTIVE	LED_ACTIVE_H
#define LED_PORTA_P1_ACTIVE	LED_ACTIVE_H
#define LED_PORTA_P2_ACTIVE	LED_ACTIVE_H
#define LED_PORTA_P3_ACTIVE	LED_ACTIVE_H
#define LED_PORTA_P4_ACTIVE	LED_ACTIVE_H
#define LED_PORTA_P5_ACTIVE	LED_ACTIVE_H
#define LED_PORTA_P6_ACTIVE	LED_ACTIVE_H
#define LED_PORTA_P7_ACTIVE	LED_ACTIVE_H

#define LED_PORTB_P0_ACTIVE	LED_ACTIVE_H
#define LED_PORTB_P1_ACTIVE	LED_ACTIVE_H
#define LED_PORTB_P2_ACTIVE	LED_ACTIVE_H
#define LED_PORTB_P3_ACTIVE	LED_ACTIVE_H
#define LED_PORTB_P4_ACTIVE	LED_ACTIVE_H
#define LED_PORTB_P5_ACTIVE	LED_ACTIVE_H
#define LED_PORTB_P6_ACTIVE	LED_ACTIVE_H
#define LED_PORTB_P7_ACTIVE	LED_ACTIVE_H

#define LED_PORTC_P0_ACTIVE	LED_ACTIVE_H
#define LED_PORTC_P1_ACTIVE	LED_ACTIVE_H
#define LED_PORTC_P2_ACTIVE	LED_ACTIVE_H
#define LED_PORTC_P3_ACTIVE	LED_ACTIVE_H
#define LED_PORTC_P4_ACTIVE	LED_ACTIVE_H
#define LED_PORTC_P5_ACTIVE	LED_ACTIVE_H
#define LED_PORTC_P6_ACTIVE	LED_ACTIVE_H
#define LED_PORTC_P7_ACTIVE	LED_ACTIVE_H

#define LED_PORTD_P0_ACTIVE	LED_ACTIVE_H
#define LED_PORTD_P1_ACTIVE	LED_ACTIVE_H
#define LED_PORTD_P2_ACTIVE	LED_ACTIVE_H
#define LED_PORTD_P3_ACTIVE	LED_ACTIVE_H
#define LED_PORTD_P4_ACTIVE	LED_ACTIVE_H
#define LED_PORTD_P5_ACTIVE	LED_ACTIVE_H
#define LED_PORTD_P6_ACTIVE	LED_ACTIVE_H
#define LED_PORTD_P7_ACTIVE	LED_ACTIVE_H


#endif /* HLED_CONFIG_H_ */
